// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/std/lib/es6/belt_Array.js";
import * as HashSet_Int from "../src/HashSet_Int.js";

var ar = Belt_Array.range(0, 16);

var s1 = Belt_Array.reduce(ar, HashSet_Int.empty, HashSet_Int.set);

var s2 = HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(HashSet_Int.remove(s1, 0), 1), 2), 3), 4), 5), 6), 7), 8), 9);

HashSet_Int.log(s2);

var e = HashSet_Int.empty;

export {
  e ,
  ar ,
  s1 ,
  s2 ,
  
}
/* ar Not a pure module */
